### ISSUE TITLE
Cannot parse CIDR mask length string: '0'

### ISSUE THREAD

**Issue by 51lver** [SixPivot/SixPivot.Azure#26]
Hello David,

Maybe it's not even a bug, but I can't get why it throws an error:
Cannot parse CIDR mask length string: '0'
At C:\Users\User\Documents\WindowsPowerShell\Modules\SixPivot.Azure\1.0.14\VNet.psm1:84 char:17
+ ...              throw "Cannot parse CIDR mask length string: '$maskLen'"
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Cannot parse CI...gth string: '0':String) [], RuntimeException
    + FullyQualifiedErrorId : Cannot parse CIDR mask length string: '0'

**I tried with a few different VNETs in different subscriptions, no luck. Any help will be appreciated**

**Comment by flcdrg** [comment]
Hi there,

the error would be coming from this bit of code:

```powershell
$addr, $maskLength = $cidrNotation -split '/'
            [int]$maskLen = 0
            if (-not [int32]::TryParse($maskLength, [ref] $maskLen)) {
                throw "Cannot parse CIDR mask length string: '$maskLen'"
            }
```

So for some reason the CIDR range that is getting passed in must have something unusual after the slash? The code assumes it is text digits as it then tries to convert that into an integer.

**Comment by 51lver** [comment]
Hey David,

After a few tests it looks like it doesn't work with VNETs with a few address spaces:

**PS C:\Users\User> echo $vnet.AddressSpace.AddressPrefixes
10.72.35.0/24
10.72.46.0/24
PS C:\Users\User> $cidrNotation = $vnet.AddressSpace.AddressPrefixes
PS C:\Users\User> $cidrNotation
10.72.35.0/24
10.72.46.0/24
PS C:\Users\User> $cidrNotation -split '/'
10.72.35.0
24
10.72.46.0
24
PS C:\Users\User> $addr, $maskLength = $cidrNotation -split '/'
PS C:\Users\User> $maskLength
24
10.72.46.0
24**

@flcdrg Any chances to add the functionality to work with such VNETs? I can try, but I'm not so experienced with Powershell so far =)

**Comment by 51lver** [comment]
I'll try to fix it on my own...

**Comment by flcdrg** [comment]
See how you go, but otherwise I can see if I can reproduce. I know I did test with a vnet with multiple addresses, but there could be something different about yours that I hadn't anticipated

**Comment by 51lver** [comment]
@flcdrg may I ask you to provide me permissions?
remote: Permission to SixPivot/SixPivot.Azure.git denied to 51lver.
fatal: unable to access 'https://github.com/SixPivot/SixPivot.Azure.git/': The requested URL returned error: 403

**Comment by dckeenan** [comment]
I'd like to throw my hat in here as well.  I always get the error if a VNet has multiple address spaces, but I also get the error periodically on others as well.  I can't find correlation with the ones that fail.  Same subscription, same address space size (/22 for example), has available space.

**Comment by johnmccormick99** [comment]
I managed to get it working by changing the sorted var to an array.

        $sorted = @($vnet.Subnets.AddressPrefix, $afterLastAvailableCidr) | Sort-Object -Property {
        # $sorted = ($vnet.Subnets.AddressPrefix + $afterLastAvailableCidr) | Sort-Object -Property {

Without this the sorted var gets set to 10.0.0.0/2310.0.4.0/31 so foreach ($cidr in $sorted) will fail

edit: so this worked when there was just one subnet on the vnet but as soon as I added a second subnet the error returned. Restoring this line then fixed it $sorted = ($vnet.Subnets.AddressPrefix + $afterLastAvailableCidr) | Sort-Object -Property {

So it seems like this line fails when there is one subnet on the vnet but it's fine when more than one
$sorted = ($vnet.Subnets.AddressPrefix + $afterLastAvailableCidr) | Sort-Object -Property

final edit:

setting this worked for one subnet or more

$sorted = @($vnet.Subnets.AddressPrefix) + $afterLastAvailableCidr | Sort-Object -Property {

**Comment by flcdrg** [comment]
Aah.. thanks for figuring that out. I'm guessing your VNet only had a single subnet in it, whereas I'd been testing with VNets with multiple subnets.
